spring.application.name=ai-service

server.port=8066

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-flash-latest
schedule.service.base-url=${SCHEDULE_SERVICE_BASE_URL:http://localhost:8084/api/v1/schedules}
management.endpoints.web.exposure.include=health,info