spring.application.name=gateway-service
server.port=8088

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.routes[0].id=test-route
spring.cloud.gateway.routes[0].uri=https://httpbin.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/test/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/test/(?<segment>.*), /${segment}
